//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 04:37:43 PM CEST 
//


package dk.frv.enav.ins.route.monalisa.se.sspa.optiroute;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.sspa.optiroute package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RouteResponse_QNAME = new QName("http://www.sspa.se/optiroute", "RouteResponse");
    private final static QName _RouteRequest_QNAME = new QName("http://www.sspa.se/optiroute", "RouteRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.sspa.optiroute
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RouteresponseType }
     * 
     */
    public RouteresponseType createRouteresponseType() {
        return new RouteresponseType();
    }

    /**
     * Create an instance of {@link Routerequest }
     * 
     */
    public Routerequest createRouterequestType() {
        return new Routerequest();
    }

    /**
     * Create an instance of {@link DirectionSpeedType }
     * 
     */
    public DirectionSpeedType createDirectionSpeedType() {
        return new DirectionSpeedType();
    }

    /**
     * Create an instance of {@link CurrentShipDataType }
     * 
     */
    public CurrentShipDataType createCurrentShipDataType() {
        return new CurrentShipDataType();
    }

    /**
     * Create an instance of {@link WaveDataType }
     * 
     */
    public WaveDataType createWaveDataType() {
        return new WaveDataType();
    }

    /**
     * Create an instance of {@link DepthPointType }
     * 
     */
    public DepthPointType createDepthPointType() {
        return new DepthPointType();
    }

    /**
     * Create an instance of {@link WeatherpointType }
     * 
     */
    public WeatherpointType createWeatherpointType() {
        return new WeatherpointType();
    }

    /**
     * Create an instance of {@link DepthPointsType }
     * 
     */
    public DepthPointsType createDepthPointsType() {
        return new DepthPointsType();
    }

    /**
     * Create an instance of {@link WeatherPointsType }
     * 
     */
    public WeatherPointsType createWeatherPointsType() {
        return new WeatherPointsType();
    }

    /**
     * Create an instance of {@link SpeedType }
     * 
     */
    public SpeedType createSpeedType() {
        return new SpeedType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteresponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sspa.se/optiroute", name = "RouteResponse")
    public JAXBElement<RouteresponseType> createRouteResponse(RouteresponseType value) {
        return new JAXBElement<RouteresponseType>(_RouteResponse_QNAME, RouteresponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Routerequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sspa.se/optiroute", name = "RouteRequest")
    public JAXBElement<Routerequest> createRouteRequest(Routerequest value) {
        return new JAXBElement<Routerequest>(_RouteRequest_QNAME, Routerequest.class, null, value);
    }

}
