//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 06:07:46 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sspa.se/optiroute", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.frv.enav.ins.route.monalisa.se.sspa.optiroute;
