//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.08 at 04:37:43 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sspa.se/optiroute", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.frv.enav.ins.route.monalisa.se.sspa.optiroute;
