//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 06:07:46 PM PDT 
//


package dk.frv.enav.ins.route.monalisa.fi.navielektro.ns.formats.vessel_waypoint_exchange;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fi.navielektro.ns.formats.vessel_waypoint_exchange package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Route_QNAME = new QName("http://www.navielektro.fi/ns/formats/vessel-waypoint-exchange", "route");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fi.navielektro.ns.formats.vessel_waypoint_exchange
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RouteType }
     * 
     */
    public RouteType createRouteType() {
        return new RouteType();
    }

    /**
     * Create an instance of {@link WaypointType }
     * 
     */
    public WaypointType createWaypointType() {
        return new WaypointType();
    }

    /**
     * Create an instance of {@link LeginfoType }
     * 
     */
    public LeginfoType createLeginfoType() {
        return new LeginfoType();
    }

    /**
     * Create an instance of {@link PositionType }
     * 
     */
    public PositionType createPositionType() {
        return new PositionType();
    }

    /**
     * Create an instance of {@link WaypointsType }
     * 
     */
    public WaypointsType createWaypointsType() {
        return new WaypointsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RouteType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navielektro.fi/ns/formats/vessel-waypoint-exchange", name = "route")
    public JAXBElement<RouteType> createRoute(RouteType value) {
        return new JAXBElement<RouteType>(_Route_QNAME, RouteType.class, null, value);
    }

}
