//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 06:07:46 PM PDT 
//


package dk.frv.enav.ins.route.monalisa.se.sspa.optiroute;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaveDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaveDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WaveDirection" type="{http://www.sspa.se/optiroute}DirectionType"/>
 *         &lt;element name="WaveHeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaveDataType", propOrder = {
    "waveDirection",
    "waveHeight"
})
public class WaveDataType {

    @XmlElement(name = "WaveDirection")
    protected float waveDirection;
    @XmlElement(name = "WaveHeight")
    protected float waveHeight;

    /**
     * Gets the value of the waveDirection property.
     * 
     */
    public float getWaveDirection() {
        return waveDirection;
    }

    /**
     * Sets the value of the waveDirection property.
     * 
     */
    public void setWaveDirection(float value) {
        this.waveDirection = value;
    }

    /**
     * Gets the value of the waveHeight property.
     * 
     */
    public float getWaveHeight() {
        return waveHeight;
    }

    /**
     * Sets the value of the waveHeight property.
     * 
     */
    public void setWaveHeight(float value) {
        this.waveHeight = value;
    }

}
