package dk.frv.enav.ins.route;

/**
 * Event types ROUTE_ACTIVATED: A new route has been activated
 * ROUTE_DEACTIVATED: The current active route has been deactivated
 * ACTIVE_ROUTE_UPDATE: There is an update to the current active route
 */
public enum RoutesUpdateEvent {
	ROUTE_ACTIVATED, ROUTE_DEACTIVATED, ACTIVE_ROUTE_UPDATE, ROUTE_CHANGED, ROUTE_ADDED, ROUTE_REMOVED, ROUTE_VISIBILITY_CHANGED, ACTIVE_ROUTE_FINISHED, METOC_SETTINGS_CHANGED, SUGGESTED_ROUTES_CHANGED, ROUTE_METOC_CHANGED, ROUTE_WAYPOINT_DELETED, ROUTE_WAYPOINT_APPENDED, ROUTE_WAYPOINT_MOVED, ROUTE_MSI_UPDATE
};
